---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: backstage-pr-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: backstage-pr-trigger-binding
      template:
        ref: backstage-pr-trigger-template