apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: backstage-pr-trigger-template
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
  - description: File content to be written (YAML)
    name: content
  - description: Entity's kind to be created
    name: entity-kind
  - description: Entity's namespace to be created
    name: entity-namespace
  - description: Entity's name to be created
    name: entity-name
  - description: CloudEvent processor
    name: cloudevent-sink
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-backstage-entity-create-
    spec:
      pipelineRef:
        name: pipeline-backstage-entity-create
      params:
      - name: target-repo
        value: git@github.ibm.com:skol/backstage-catalog.git
      - name: repo-github-api-host
        value: api.github.ibm.com
      - name: repo-name
        value: skol/backstage-catalog
      - name: entity-kind
        value: $(tt.params.entity-kind)
      - name: entity-namespace
        value: $(tt.params.entity-namespace)
      - name: entity-name
        value: $(tt.params.entity-name)
      - name: content
        value: $(tt.params.content)
      - name: cloudevent-sink
        value: $(tt.params.cloudevent-sink)
      - name: git-pat-secret-name
        value: ghe-token
      serviceAccountName: pipeline
      timeout: 1h0m0s
      workspaces:
      - name: git-output
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Mi
            storageClassName: ocs-storagecluster-cephfs
            volumeMode: Filesystem
      - name: ssh-directory
        secret:
          secretName: ssh-creds
