apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  data:
    - secretKey: pat
      remoteRef:
        key: 670d8bbd-6c5e-3002-d4cf-41f6e80941eb
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ghe-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .pat | toString }}"
