apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  data:
    - secretKey: pat
      remoteRef:
        key: 2852194b-f6b4-f5cc-0aaf-4121e80ad7d1
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ghe-token
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        token: "{{ .pat | toString }}"
