apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: vault-subscription
  namespace: vault 
  labels:
    app: vault
  annotations:
      apps.open-cluster-management.io/git-branch: master
      apps.open-cluster-management.io/git-path: clusters/cluster-services/vault/manifests/ 
      apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: vault/vault-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: vault-placement-1
#      apiGroup: apps.open-cluster-management.io