apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssh-credentials-secret
spec:
  data:
    - secretKey: id_rsa
      remoteRef:
        key: d0eb6d2e-3495-434d-fb76-be7efb5c0200
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: ghe-ssh-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        id_rsa: "{{ .id_rsa | toString }}"
