---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-pak-deployer-config-{{ .Values.clusterName }}-{{ .Values.projectName }}
  namespace: cloud-pak-deployer
data:
  cpd-config.yaml: |
    {{- .Values.configYaml | nindent 4 -}}
