kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-view
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: machinepools-pipeline
  - kind: ServiceAccount
    name: pipeline
    namespace: gitops-repo-deploy-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view